version: '3.5'

services:
  streamlit-app:
    build: .
    command: "/bin/sh /usr/src/app/start.sh"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8501:8501"
    restart: on-failure
    depends_on:
#      - chromadb
      - weaviate
      - mongodb
    networks:
      - chatty-network
#
#  chromadb:
#    image: chromadb/chroma
#    volumes:
#      - chatty-volume:/data/db
#    ports:
#      - "8000:8000"
#    networks:
#      - chatty-network

  mongodb:
    image: mongo:latest
    volumes:
      - chatty-volume:/data/db
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - chatty-network

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.23.7
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - chatty-volume:/var/lib/weaviate
    networks:
      - chatty-network
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'



networks:
  chatty-network:

volumes:
  chatty-volume: