name: chatty
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip==24.0
  - numpy==1.26.4
  - openai==1.37.0
  - tiktoken==0.7.0
  - streamlit==1.36.0
  - bcrypt==4.2.0
  - pymongo==4.6.1
  - captcha==0.6.0
  - ijson==3.3.0
  - sentence-transformers==3.0.1
  - nest-asyncio==1.6.0
  - flask==3.0.3
  - python-dotenv==1.0.1
  - pytorch==2.3.1
  - pip:
    - streamlit-feedback==0.1.3
    - protobuf==4.25.1
    - weaviate-client==4.5.0
    - latexcodec==3.0.0
    - pylatexenc==3.0a25
    - bibtexparser --pre